export enum EGenre {
  Action = 'action',
  Adventure = 'adventure',
  Animation = 'animation',
  Comedy = 'comedy',
  Crime = 'crime',
  Documentary = 'documentary',
  Drama = 'drama',
  Family = 'family',
  Fantasy = 'fantasy',
  History = 'history',
  Horror = 'horror',
  Music = 'music',
  Mystery = 'mystery',
  Romance = 'romance',
  ScienceFiction = 'science-fiction',
  TvMovie = 'tv-movie',
  Thriller = 'thriller',
  War = 'war',
}

export const genres = [
  EGenre.Action,
  EGenre.Adventure,
  EGenre.Animation,
  EGenre.Comedy,
  EGenre.Crime,
  EGenre.Documentary,
  EGenre.Drama,
  EGenre.Family,
  EGenre.Fantasy,
  EGenre.History,
  EGenre.Horror,
  EGenre.Music,
  EGenre.Mystery,
  EGenre.Romance,
  EGenre.ScienceFiction,
  EGenre.TvMovie,
  EGenre.Thriller,
  EGenre.War,
];

export const genresIcons = {
  [EGenre.Action]: '🔥',
  [EGenre.Adventure]: '🏞️',
  [EGenre.Animation]: '🐭',
  [EGenre.Comedy]: '😂',
  [EGenre.Crime]: '👮',
  [EGenre.Documentary]: '📽️',
  [EGenre.Drama]: '🎭',
  [EGenre.Family]: '👪',
  [EGenre.Fantasy]: '🧙',
  [EGenre.History]: '📜',
  [EGenre.Horror]: '👻',
  [EGenre.Music]: '🎵',
  [EGenre.Mystery]: '🔍',
  [EGenre.Romance]: '💕',
  [EGenre.ScienceFiction]: '👽',
  [EGenre.TvMovie]: '📺',
  [EGenre.Thriller]: '🔪',
  [EGenre.War]: '🔫',
};
